settings:
  respawnToHome: true
  bedsCanSetHome: 0
  bedsDuringDay: false
  loadChunks: false
  locale: 'en'
  useColors: true
  enableInvite: true
  enableDenyPerm: false
  enableSethome: true
  debugLog: false
  downloadLibs:
    enable: true
    mysqlLib: true
    sqliteLib: true
  mysql:
    enable: false
    connection: 'jdbc:mysql://localhost:3306/minecraft'
    username: 'minecraft'
    password: 'password'
defaults:
  homeLimit: 3
  homeInvLimit: 1
  warmup: 0
  cooldown: 0
homeLimits:
  a: 30
  b: 20
  c: 15
  d: 10
  e: 5
homeInvLimits:
  a: 10
  b: 8
  c: 6
  d: 4
  e: 2
timers:
  timerByPerms: false
  additionalTime: false
  cooldownNotify: false
  warmupNotify: true
  abortOnDamage: 0
  abortOnMovement: false
  cooldowns:
    a: 0
    b: 5
    c: 10
    d: 15
    e: 20
  warmups:
    a: 0
    b: 5
    c: 10
    d: 15
    e: 20