name: MyHome
version: 1.9.4c
author: tkelly and spathizilla
main: me.taylorkelly.myhome.MyHome
commands:
  home:
    description: All of the MyHome commands
    usage: /<command> help - Displays the MyHome commands