name: uHome
version: 1.4.1
author: ks07
authors: [spathizilla, tkelly]
main: uk.co.ks07.uhome.uHome
website: http://www.ultimateminecraft.net/
commands:
  home:
    description: Access to the home commands.
    usage: /<command> help [page] - Displays the uHome commands
  sethome:
    description: Alias for /home set
    usage: /<command> - Sets the home position.
    permission: uhome.own.set
permissions:
  uhome.all:
    description: Gives access to all uHome commands.
    children:
      uhome.admin: true
      uhome.own: true
      uhome.bypass: true
  uhome.own:
    description: Gives access to all uHome commands
    default: true
    children:
      uhome.own.set: true
      uhome.own.warp: true
      uhome.own.delete: true
      uhome.own.list: true
      uhome.own.listinvites: true
      uhome.own.invite: true
      uhome.own.uninvite: true
  uhome.own.set:
    description: Allows you to set homes.
  uhome.own.warp:
    description: Allows you to warp to your homes.
  uhome.own.delete:
    description: Allows you to delete your warps.
  uhome.own.list:
    description: Allows you to list your warps.
  uhome.own.listinvites:
    description: Allows you to list both sent and received invites.
  uhome.own.invite:
    description: Allows you to invite others to your homes.
  uhome.own.uninvite:
    description: Allows you to uninvite others from your homes.
  uhome.admin:
    description: Gives access to all uHome admin commands
    default: op
    children:
      uhome.admin.warp: true
      uhome.admin.set: true
      uhome.admin.delete: true
      uhome.admin.list: true
      uhome.admin.listinvites: true
      uhome.admin.reload: true
      uhome.admin.info: true
  uhome.admin.set:
    description: Allows you to set other people's homes.
  uhome.admin.warp:
    description: Allows you to warp to other's homes.
  uhome.admin.delete:
    description: Allows you to delete other's warps.
  uhome.admin.list:
    description: Allows you to list other's warps.
  uhome.admin.listinvites:
    description: Allows you to list other's sent and received invites.
  uhome.admin.reload:
    description: Allows you to reload uHome.
  uhome.admin.info:
    description: Allows you to lookup a home's location.
  uhome.bypass:
    description: Allows you to bypass all restrictions.
    default: op
    children:
      uhome.crossworld: true
      uhome.bypass.bed: true
      uhome.bypass.cooldown: true
      uhome.bypass.warmup: true
      uhome.bypass.limit: true
  uhome.bypass.bed:
    description: Allows you to bypass the bed restriction in the config.
  uhome.bypass.cooldown:
    description: Allows you to bypass the warp cooldown.
  uhome.bypass.warmup:
    description: Allows you to bypass the warp warm-up.
    children:
      uhome.bypass.warmup.damage: true
      uhome.bypass.warmup.movement: true
  uhome.bypass.warmup.damage:
    description: Prevents damage from cancelling your warm-up.
  uhome.bypass.warmup.movement:
    description: Prevents movement from cancelling your warm-up.
  uhome.bypass.limit:
    description: Allows you to bypass all warp limits.
  uhome.limit.a:
    description: Gives the player the warp limit a set in the config.
  uhome.limit.b:
    description: Gives the player the warp limit b set in the config.
  uhome.limit.c:
    description: Gives the player the warp limit c set in the config.
  uhome.limit.d:
    description: Gives the player the warp limit d set in the config.
  uhome.limit.e:
    description: Gives the player the warp limit e set in the config.
  uhome.warmup.a:
    description: Gives the player the warmup time a set in the config.
  uhome.warmup.b:
    description: Gives the player the warmup time b set in the config.
  uhome.warmup.c:
    description: Gives the player the warmup time c set in the config.
  uhome.warmup.d:
    description: Gives the player the warmup time d set in the config.
  uhome.warmup.e:
    description: Gives the player the warmup time e set in the config.
  uhome.cooldown.a:
    description: Gives the player the cooldown time a set in the config.
  uhome.cooldown.b:
    description: Gives the player the cooldown time b set in the config.
  uhome.cooldown.c:
    description: Gives the player the cooldown time c set in the config.
  uhome.cooldown.d:
    description: Gives the player the cooldown time d set in the config.
  uhome.cooldown.e:
    description: Gives the player the cooldown time e set in the config.
  uhome.deny:
    description: Removes access to uHome - fix for ticket 8 on DBO.
  uhome.crossworld:
    description: Allows the player to warp across worlds.